### ISSUE TITLE
[FEATURE] 프로젝트 기본 세팅

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#1]
## 제목
프로젝트 구성을 위한 기본 세팅

## ToDo
- [x] 폴더 구분
- [x] 공용으로 사용할 코드 작성
- [x] 리덕스 스토어 연결
- [x] 리덕스 사가 연결
- [x] 라이브러리 설치
