### ISSUE TITLE
[STYLE] css 수정

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#112]
## 설명
- 디자인 요청 사항 수정

## ToDo
- [ ] 알라 카드 글씨 굵기 조정
- [ ] 헤더에서 아이콘 클릭시, 헤더와 본문이 벌어진다.
- [x] LeftSide 버튼과 글씨 정렬 + 링크

**Comment by 11t518s** [comment]
@yoon-junseo 이거 닫아도 될듯?
