### ISSUE TITLE
[FIX] 카드 세팅

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#117]
## 설명
- 카드 세팅 부분 수정사항

## ToDo
- [x] 카드 세팅 수정 이후, 완료 메시지 토스트 팝업
- [x] Title 문구 변경
- [x] 배경 선택 글자색 변경
- [x] secret 카드일때만 도움말 표시
