### ISSUE TITLE
[REFACTOR] 코드 제거

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#131]
## 설명
- 배포를 위한 준비

## ToDo
- [ ] 안 쓰는 코드 제거
- [ ] console.log 제거
- [ ] 리덕스 dev tool 제거
