### ISSUE TITLE
[FEATURE] 스켈레톤 UI

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#137]
## 설명
- 로딩 화면에 스켈레톤 UI를 적용

## ToDo
- [x] mypage
- [x] 친구 페이지
- [x] 알라 카드 리스트 페이지
- [ ] 알라카드 세팅 페이지
- [ ] 프로필 세팅 페이지
- [ ] 셀렉트 페이지
