### ISSUE TITLE
[FIX] 배포전 디자인 QA

### ISSUE THREAD

**Issue by 11t518s** [dnd-side-project/dnd-5th-5-frontend#144]
## todos

- [x] footer
- [x] leftside
- [x] font
- [x] emoji
- [x] 단어 줄 바꿈
- [x] 버튼, 토글, 토스트 : 회원정보, 카드관리
- [ ] 프로필 세팅 choose file 버튼 가리기
- [ ] 회원탈퇴 모달 폰트 줄건격,, 체크박스 이미지
- [ ] 프로필 세팅 폰트 크기 고정
- [ ] 카드관리 : 저장할래 disabled, 알라카드 물음표 설명 위치, 백그라운드 체크표시
- [ ]  키워드 픽 손모양 커서, 셀렉뷰 헤더
