### ISSUE TITLE
[FIX] QA

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#149]
## 설명
- 디자인 QA
- 기능 QA

## ToDo
- [x] 사용중에 로그인하면 모달 닫히게 하기
- [x] friend modal에서 로딩중일때 빈 태그 넘기기 -> 모달이 뜨는 시간이 지연 된다. 그냥 component에서 스피너를 줘서 로딩중임을 보여주는게 나을듯
- [x] 약관 링크
- [x] 친구 모달에서 기본 프로필 테두리
- [x] 요청하기 토스트 팝업 살짝 위로 이동
- [x] 메인 페이지 로고 고정 픽셀
- [x] 메인 페이지 텍스트 줄 간격
- [x] 로그인 버튼 높이 간격 동일하게, 그림자 값
- [x] 알람 없을때 가운데에 위치
- [x] 알람에 시간 추가
- [x] 알림이 없을때 알림 누르면 에러
- [x] 알람에서 친구 관련은 친구 수락 삭제만 남기고, 다른 거는 링크로 
- [x] 알람 사이에 보더 1px 라인
