### ISSUE TITLE
[FEATURE] 친구창 모달

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#16]
## 설명
- 헤더의 사람 아이콘을 누르면 친구창 모달이 나온다.
- 친구가 없는 경우, 있는 경우를 고려해서 만들어야 한다.
- 알람창과 같은 모달 사용

## ToDo
- [x] 친구가 없는 경우, 레이아웃
- [x] 친구가 없는 경우, 디자인
- [x] 친구가 있는 경우, 레이아웃
- [x] 친구가 있는 경우, 디자인
- [x] API 연동

## 추가 사항
- 기능 개발 완료 후, 리팩토링
- 헤더 완성 후, 헤더와 연결
