### ISSUE TITLE
[FIX] QA

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#169]
## 설명
- 디자인 QA

## ToDo
- [x] 카카오 아이콘 크기 줄여주기
- [x] 알람에 알라 아이콘 넣어주기
- [x] 로그인 X 버튼 위치 조정
