### ISSUE TITLE
[FIX] 프로필 세팅 이메일 아이콘

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#172]
## 설명
- 프로필 세팅 이메일 아이콘 수정

## ToDo
- [x] 아이콘 wrapper 추가
- [x] provider를 확인하는 state 추가
- [x] 이메일 아이콘 크기 수정
