### ISSUE TITLE
[FEATURE] 헤더와 친구, 알림창 연결

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#25]
## 설명
- 헤더의 친구창, 알림창 연결
- 이미지가 있다면 프로필 이미지로, 없다면 기본 이미지로

## ToDo
- [x] 친구창 연결
- [ ] 알림창 연결
- [x] 프로필 이미지 적용 (개인 or 기본)
- [x] 로고 링크 연결
- [x] 프로필 이미지 클릭시, 프로필 정보 보여주는 모달
- [x] 데스크탑 UI

## 추가
- [ ] 로그인 안한 경우, 친구창과 알림창 UI

**Comment by yoon-junseo** [comment]
알림창 완료 되면 알림창도 연결 (알림창 API는 후순위)

**Comment by yoon-junseo** [comment]
남은 일
1. 데스크탑 프로필 UI
2. 기능
