### ISSUE TITLE
[FEATURE] 라우터 

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#26]
## 설명
- 로그인한 상태라면, 메인 페이지 접근 시, 마이페이지로 이동시킨다.

## ToDo
- [x] 리다이렉션
- [x] 로그인을 했는데 / 로 접근하려는 경우, 자기 페이지로 리다이렉션
- [x] 로그인을 하지 않았던가, 다른 사람 세팅 페이지로 이동하려는 경우, / 로 리다이렉션 -> 로그인 한 경우에는 자기 페이지로 리다이렉션
- [x] 사용자를 확인하는 커스텀훅

**Comment by yoon-junseo** [comment]
- 세팅 관련 페이지에서 해당 유저인지 확인하는 절차가 필요함
1. 현재는 스토어에 사용자 정보가 들어있는데, 새로 고침을 하면  사라지기 때문에 web storage에 저장해뒀다. 그렇기 때문에 스토어에 사용자 정보가 없다면 web storage에서 꺼내와서 Link를 부여하는 방식 (세션에 값을 넣으면 본인 세팅 페이지가 아니여도 접근이 가능하다.)
2. 헤더에서 세팅 페이지로 넘어갈 수 있는 Link가 있기 때문에, 헤더에서 사용자 정보가 없는 경우, 사용자 정보를 받아오는 API를 요청하는 방식으로 url의 닉네임과 스토어의 닉네임이 다르면 Link를 걸어주지 않는 방식
