### ISSUE TITLE
[FEATURE] 카드 세팅

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#27]
## 설명
- 알라 카드 리스트에서 카드 클릭시, 해당 카드 세팅을 수정하는 페이지로 이동한다.

## ToDo
- [x] 카드 클릭시, 해당 카드와 관련된 정보를 리덕스에 올린다.
- [x] 모바일 UI
- [x] 데스크탑 UI
- [x] 서버에서 카드 정보 받아오기
- [x] 수정된 내용 patch
- [x] 카드가 완성되지 않은 경우, 카드 클릭 막기

## 고려사항
- 이미지 파일이 커서 로딩 속도가 느릴 것 같다. 일단 서버에서 받아와보고, 느리다면 
1. 이미지 압축, 크기 조정
2. 프론트에서 이미지를 업로드 해보는 방식
- 완성된 카드의 경우 폰트 컬러를 흰색 고정으로 갈건지..?
