### ISSUE TITLE
[STYLE] 반응형 수정

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#36]
## 설명
- 알라 카드 리스트 css 수정
- 전체적인 css 수정
## ToDo
- [x] 헤더 부분
- [x] 알라 카드 리스트 부분
- [x] 마이페이지 부분
- [x] 로그인 데스크탑 스타일 수정
- [x] 친구 모달 (친구 X)
- [x] 친구 모달 (친구 O)
