### ISSUE TITLE
[FIX] 프로필 세팅 추가 작업

### ISSUE THREAD

**Issue by 11t518s** [dnd-side-project/dnd-5th-5-frontend#57]
## ToDo

- [ ] 쿠키 초기화(이게 익스파이어 주는대도 안됨)
- [ ] 반응형 vh vw으로 맞추기
- [x] 버튼 애니매이션으로 맞추기
- [ ] 프로필 이미지 크기 맞추기
- [x] 아이거 닉네임 수정 할 때 자신의 닉네임을 유지하는 것도 안됨(자신 닉네임과 동일하면 exists true나도 설정할 수 있게 )
