### ISSUE TITLE
[FIX] 1차 QA

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#65]
## 설명
- QA

## ToDo
- [x] 알라카드 클릭시 넘어가는 세팅 페이지의 url의 수정
- [x] 마이페이지 알라 카드 자동으로 넘어가게
- [x] 친구 모달 창 mock data 제거
- [x] 마이페이지에서 클립 보드 클릭 누르면 토스트 팝업 만들기
- [x] 없는 닉네임으로 데이터 받아오면 에러 뜨는거 수정하기
- [x] 로그인 모달에서 콘솔 로그 제거
- [x] setting router 수정
- [x] button hover 아이콘 색상 변경
- [x] 프로필 
- [x] 친구 페이지
- [ ] 헤더 수정 #64 
- [x] 카드 세팅 페이지에서 잠금 버튼 반대로 되어있음

**Comment by yoon-junseo** [comment]
친구 페이지
1. 해당 페이지 유저의 정보를 확인하는 api 나오면 맞게 해주기
